### PR TITLE
Decomposed n-qubit mcx without approximation

### PR DESCRIPTION
**Pull request by rafaella-vale**
Implementation based on Decompositions of n-qubit Toffoli Gates with Linear Circuit Complexity by He et al. (2017)

### CODE REVIEW

**Comment by adjs** [comment]
Thanks @rafaella-vale , 

Could you add a test for the function `mcx_gate`?

**Comment by rafaella-vale** [comment]
Tests included for both mcx functions.

**Comment by israelferrazaraujo** [comment]
Hello, @rafaella-vale and @adjs .

Please evaluate the feasibility of including a function to estimate the number of CNOTs needed for the MCX constructions (with and without ancilla).
Something similar is present in the Unitary and Isometry gates, as in the Low-rank state preparation.
This function is important to determine the cost of the operation without the need to build the circuit.

Thanks for the great work.

**Comment by adjs** [comment]
Closed in favor of PR #128

**Pull request closed without merging**
