### PR TITLE
Removes use of Qiskit to calculate diagonal

### PR DESCRIPTION
**Pull request by israelferrazaraujo**
Removes use of Qiskit in `UCGEInitialize` to calculate diagonals

### CODE REVIEW

**Comment by israelferrazaraujo** [comment]
I assumed that `ctrl_qc` is always continuous. If this is not true, the `_tensor_product_diagonal` function needs to be modified accordingly.

**Comment by israelferrazaraujo** [comment]
I would like to suggest adding comments to the code of the `UCGEInitialize` class.

**Comment by israelferrazaraujo** [comment]
All the matrices used in the `_tensor_product_diagonal` function are highly sparse. So it might be better to use sparse operations.

**Comment by adjs** [comment]
thanks, @israelferrazaraujo . On hold.

**Comment by israelferrazaraujo** [comment]
Replaced by PR #178.

**Pull request closed without merging**
