### PR TITLE
add class Initialize

### PR DESCRIPTION
**Pull request by israelferrazaraujo**

### CODE REVIEW

**Comment by adjs** [comment]
Thanks, @israelferrazaraujo. I modified the purpose of this PR. An Initialize class is being added in order to standardize all state preparation algorithms.

**Comment by israelferrazaraujo** [comment]
We need to think about the case where the circuit produced by the algorithm has a variable number of qubits, such as BDSP.

**Comment by IsmaelCesar** [comment]
> We need to think about the case where the circuit produced by the algorithm has a variable number of qubits, such as BDSP.

Algorithms that take a statevector as an input, the number of qubits can be inferred by it's size. However, the caveat is, if the user does not gives a 2^n sized vector, we could either concatenate the missing slots with a list with zero values transforming it into a 2^n sized vector, or we could raise and error and force the user to input a properly sized vector. I personally prefer the second option, thus we can avoid errors that can arise from dinamically type checking everything. And if that's the case we can apply that to cases in which different algorithm get different inputs, like the implementation of the Gleining's algorithm gets a dictionary, whereas Ventura's and  Möttönen's get a state vector.

**Comment by israelferrazaraujo** [comment]
> Algorithms that take a statevector as an input, the number of qubits can be inferred by it's size.

The number of qubits in the BDSP circuit not only depends on the length of the input vector but also on an optimization parameter. For the sparse version of the BDSP, determining the number of qubits is even more complicated. It is necessary to decompose the state.

**Review by IsmaelCesar — APPROVED** [review]

**Pull request merged**
